### ISSUE TITLE
[Flatpak] Don't use a hard link to system_bus_socket. Is it possible? 

### ISSUE THREAD

**Issue by proninyaroslav** [canonical/dbus.dart#260] opened 2021-08-16 18:39 UTC
By default, Flatpak apps are isolated from the system bus, the usual option is to explicitly specify the required DBus interface (for example, `org.freedesktop.Notifications`). All calls on this interface are proxied using [xdg-dbus-proxy](https://github.com/flatpak/xdg-dbus-proxy). 

The problem is that in the case of the `dbus` package (`DBusClient.system()`), it's impossible to proxy the system bus in this way, because the system socket path is actually used. Since by default Flatpak apps are isolated from the filesystem and the system bus, we get this exception:

`flutter: SocketException: Connection failed (OS Error: No such file or directory, errno = 2), address = /run/dbus/system_bus_socket, port = 0`

The only solution is to allow access to the system socket (option `--socket=system-bus` when building the package), but the Flatpak convention considers this permission dangerous https://docs.flatpak.org/en/latest/sandbox-permissions.html#d-bus-access.

I can't say for sure if a portable way to specify the system bus socket is possible (as in the case of a session socket using XDG paths), but it would be very useful. Or does this require replacing `DBusClient.system()` with `DBusClient.session()` in plugins that use it?

**Comment by robert-ancell** [comment] 2021-08-16 21:24
I thought I was doing what the [D-Bus specification](https://dbus.freedesktop.org/doc/dbus-specification.html) stated, which is to check `$DBUS_SYSTEM_BUS_ADDRESS` and default to `/run/dbus/system_bus_socket`. However, now I check again it's supposed to be `/var/run`, which I have fixed in https://github.com/canonical/dbus.dart/pull/261. Perhaps that will now be suitably handled in a Flatpak?

**Comment by barthalion** [comment] 2021-08-17 06:58
Hey Robert, any idea why is access to the system bus required at all? I don't think the problem is the socket location, it's just that it's not available at all unless permitted in Flatpak.

**Comment by proninyaroslav** [comment] 2021-08-17 07:06
@barthalion 
The system bus is used in some packages such as [connectivity_plus](https://pub.dev/packages/connectivity_plus), [nm](https://pub.dev/packages/nm) and [battery_plus](https://pub.dev/packages/battery_plus). All these packages are in the top use among developers and there is no way to refuse it.

**Comment by barthalion** [comment] 2021-08-17 07:18
This is valid for applications requiring these features. Tracking UPS and Russian Post packages requires none of this in practice.

**Comment by barthalion** [comment] 2021-08-17 07:21
In fact, if I run LibreTrack with `--log-system-bus`, nothing ever gets logged. Not every application requires direct access to system bus.

**Comment by proninyaroslav** [comment] 2021-08-17 07:42
@barthalion 
Why are you so sure about this? I use `connectivity_plus` to test the Internet connection before making any HTTP requests. Once a connection is available, a request queue will be sent.

**Comment by proninyaroslav** [comment] 2021-08-17 07:47
And also `connectivity_plus` uses the system bus to listen for `org.freedesktop.NetworkManager` events.

**Comment by barthalion** [comment] 2021-08-17 07:48
@robert-ancell We will take the discussion back to Flathub as it doesn't make sense to pollute it here. Sorry for the noise.

**Comment by proninyaroslav** [comment] 2021-08-17 08:25
@robert-ancell 
It seems that the fixes in 0.5.5 helped to use the `--system-talk-name` option to proxy system DBus events. Before that, I was getting a `SocketException` every time.

**Comment by robert-ancell** [comment] 2021-08-17 23:04
I've released the system default address fix in dbus 0.5.6.

I'm going to close this issue for now, as I'm confident we're doing what the D-Bus specification requires and the same as GLib is. If there's an issue in a Flatpak, that must be because it either doesn't have suitable permissions to access the system bus, or Dart libraries that use D-Bus aren't handling the case where the bus is not accessible. Please re-open if future information indicates that there needs to be a change made to dbus.dart.

Thanks!

**Closed as completed by robert-ancell** 2021-08-17 23:04 UTC
